version: '3'

services:

  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
      - "5100:5100"
    volumes:
      - ./flask-app/instance:/app/flask-app/instance
      - ./flask-app/static/images:/app/flask-app/static/images
    environment:
      # - DATABASE_URL=mysql://wisp:wisp@db:3306/wisp?charset=utf8mb4
      - DATABASE_URL=sqlite:///wisp.db
      - JWT_SECRET_KEY=you-secret-key
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASSWORD=admin123
  
  react-app:
    build: ./react-app
    container_name: react-app
    ports:
      - "5180:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./flask-app/static/images:/var/www/static/images
    depends_on:
      - flask-app

  # db:
  #   image: mysql:latest
  #   container_name: database
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: wisp
  #     MYSQL_USER: wisp
  #     MYSQL_PASSWORD: wisp
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - "3316:3306"
  