version: '3'

services:

  flask-server:
    build: ./flask-server
    container_name: flask-server
    ports:
      - "5100:5100"
    volumes:
      - ./flask-server/instance:/app/flask-server/instance
      - ./flask-server/static/images:/app/flask-server/static/images
    environment:
      - DATABASE_URL=sqlite:///wisp.db
      - JWT_SECRET_KEY=you-secret-key
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASSWORD=admin123
  
  react-app:
    build: ./react-app
    container_name: react-app
    ports:
      - "5180:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./flask-server/static/images:/var/www/static/images
    depends_on:
      - flask-server
