"""empty message

Revision ID: 27fccf014785
Revises: 6a0e67f31c63
Create Date: 2023-04-23 17:51:50.712525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27fccf014785'
down_revision = '6a0e67f31c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', 'PRIVATE'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('enable_comment',
               existing_type=mysql.ENUM('enable', 'disable'),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('enable_comment',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('enable', 'disable'),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', 'PRIVATE'),
               existing_nullable=True)

    # ### end Alembic commands ###
