"""timestamp

Revision ID: 841edbe47328
Revises: c1baee8b523b
Create Date: 2023-04-21 15:20:13.265831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841edbe47328'
down_revision = 'c1baee8b523b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
