"""post tag  table -2 

Revision ID: c1baee8b523b
Revises: 13136e3f83e1
Create Date: 2023-04-21 12:03:25.312229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1baee8b523b'
down_revision = '13136e3f83e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=255), nullable=True))
        batch_op.alter_column('enable_comment',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('enable', 'disable', name='enablecomment'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('enable_comment',
               existing_type=sa.Enum('enable', 'disable', name='enablecomment'),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
